server:
  port: 8082

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true #开启请求方式前缀
      datasource:
        ds2: #配置文件的的数据源
          nacos:
            server-addr: 192.168.137.129:8848
            data-id: degrade.json
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: degrade


hm:
  db:
    database: hm-cart
  swagger:
    title: "黑马商城购物车接口文档"
    package: com.hmall.cart.controller
    description: "黑马商城购物车接口文档"


